# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'final_application' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for final_application
  pod 'Firebase/Core'
  pod 'Firebase/Auth’
pod 'Firebase/Database’
pod 'Firebase/Storage’
pod ‘SwiftKeychainWrapper’


  target 'final_applicationTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'final_applicationUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
